[Settings]
; Refresh your skin ... [!Refresh *] will refresh all
RefreshCommand=[!RefreshGroup TronMCP]
; Name displayed in the Taskbar area
TaskbarTitle=Configure Tron MCP
; Window width; should match HeaderImage width
PanelWidth=400
; Window height
PanelHeight=700
; Estimated height of description area; will vary with Font style and size
DescriptionLines=2
; Select Header Image to match PanelWidth (Height should be 60 px)
HeaderImage=header.jpg

; List of files to search variables into
[Files]
File1=..\..\Variables.inc

; List of editable variables with their description
[Variables]
BgWidth=Width of the background skin
BgHeight=Height of the background skin
WeatherQ=Weather query for openweathermap.org
WeatherApiKey=API key for openweathermap.org
Latitude=Location latitude (find it on latlong.net)
Longitude=Location longitude (find it on latlong.net)
Drive1=Drive letter for drive 1
Drive2=Drive letter for drive 2
Drive3=Drive letter for drive 3
Drive4=Drive letter for drive 4
Drive5=Drive letter for drive 5
Drive6=Drive letter for drive 6
CPUTDP=TDP of your CPU
GPUTDP=TDP of your GPU
CPUClockSensorId=HWiNFO SensorId for CPU Clock
CPUClockSensorInstance=HWiNFO SensorInstance for CPU Clock
CPUClockEntryId=HWiNFO EntryId for CPU Clock
CPUTempSensorId=HWiNFO SensorId for CPU Temperature
CPUTempSensorInstance=HWiNFO SensorInstance for CPU Temperature
CPUTempEntryId=HWiNFO EntryId for CPU Temperature
CPUPowerSensorId=HWiNFO SensorId for CPU Power
CPUPowerSensorInstance=HWiNFO SensorInstance for CPU Power
CPUPowerEntryId=HWiNFO EntryId for CPU Power
GPUClockSensorId=HWiNFO SensorId for GPU Clock
GPUClockSensorInstance=HWiNFO SensorInstance for GPU Clock
GPUClockEntryId=HWiNFO EntryId for GPU Clock
GPUTempSensorId=HWiNFO SensorId for GPU Temperature
GPUTempSensorInstance=HWiNFO SensorInstance for GPU Temperature
GPUTempEntryId=HWiNFO EntryId for GPU Temperature
GPUUsageSensorId=HWiNFO SensorId for GPU Usage
GPUUsageSensorInstance=HWiNFO SensorInstance for GPU Usage
GPUUsageEntryId=HWiNFO EntryId for GPU Usage
GPUMemSensorId=HWiNFO SensorId for GPU Memory Allocated
GPUMemSensorInstance=HWiNFO SensorInstance for GPU Memory Allocated
GPUMemEntryId=HWiNFO EntryId for GPU Memory Allocated
GPUMemUsageSensorId=HWiNFO SensorId for GPU Memory Usage
GPUMemUsageSensorInstance=HWiNFO SensorInstance for GPU Memory Usage
GPUMemUsageEntryId=HWiNFO EntryId for GPU Memory Usage
GPUPowerSensorId=HWiNFO SensorId for GPU Power
GPUPowerSensorInstance=HWiNFO SensorInstance for GPU Power
GPUPowerEntryId=HWiNFO EntryId for GPU Power
Drive1TempSensorId=HWiNFO SensorId for Drive1 Temperature
Drive1TempSensorInstance=HWiNFO SensorInstance for Drive1 Temperature
Drive1TempEntryId=HWiNFO EntryId for Drive1 Temperature
Drive2TempSensorId=HWiNFO SensorId for Drive2 Temperature
Drive2TempSensorInstance=HWiNFO SensorInstance for Drive2 Temperature
Drive2TempEntryId=HWiNFO EntryId for Drive2 Temperature
Drive3TempSensorId=HWiNFO SensorId for Drive3 Temperature
Drive3TempSensorInstance=HWiNFO SensorInstance for Drive3 Temperature
Drive3TempEntryId=HWiNFO EntryId for Drive3 Temperature
Drive4TempSensorId=HWiNFO SensorId for Drive4 Temperature
Drive4TempSensorInstance=HWiNFO SensorInstance for Drive4 Temperature
Drive4TempEntryId=HWiNFO EntryId for Drive4 Temperature
Drive5TempSensorId=HWiNFO SensorId for Drive5 Temperature
Drive5TempSensorInstance=HWiNFO SensorInstance for Drive5 Temperature
Drive5TempEntryId=HWiNFO EntryId for Drive5 Temperature
Drive6TempSensorId=HWiNFO SensorId for Drive6 Temperature
Drive6TempSensorInstance=HWiNFO SensorInstance for Drive6 Temperature
Drive6TempEntryId=HWiNFO EntryId for Drive6 Temperature
SysFan1SensorId=HWiNFO SensorId for system fan 1
SysFan1SensorInstance=HWiNFO SensorInstance for system fan 1
SysFan1EntryId=HWiNFO EntryId for system fan1
SysFan2SensorId=HWiNFO SensorId for system fan 1
SysFan2SensorInstance=HWiNFO SensorInstance for system fan 1
SysFan2EntryId=HWiNFO EntryId for system fan1
SysFan3SensorId=HWiNFO SensorId for system fan 1
SysFan3SensorInstance=HWiNFO SensorInstance for system fan 1
SysFan3EntryId=HWiNFO EntryId for system fan1
SysFan4SensorId=HWiNFO SensorId for system fan 1
SysFan4SensorInstance=HWiNFO SensorInstance for system fan 1
SysFan4EntryId=HWiNFO EntryId for system fan1
MOSTempSensorId=HWiNFO SensorId for MOS Temperature
MOSTempSensorInstance=HWiNFO SensorInstance for MOS Temperature
MOSTempEntryId=HWiNFO EntryId for MOS Temperature
PCHTempSensorId=HWiNFO SensorId for PCH Temperature
PCHTempSensorInstance=HWiNFO SensorInstance for PCH Temperature
PCHTempEntryId=HWiNFO EntryId for PCH Temperature
SysTemp1SensorId=HWiNFO SensorId for system Temperature 1
SysTemp1SensorInstance=HWiNFO SensorInstance for system Temperature 1
SysTemp1EntryId=HWiNFO EntryId for system Temperature 1
SysTemp2SensorId=HWiNFO SensorId for system Temperature 2
SysTemp2SensorInstance=HWiNFO SensorInstance for system Temperature 2
SysTemp2EntryId=HWiNFO EntryId for system Temperature 2
