[Variables]

CPUTDP=95
GPUTDP=160

; HWiNFO Config (https://www.hwinfo.com/forum/Thread-Rainmeter-plug-in-for-HWiNFO-3-2)
CPUClockSensorId=0xf0000300
CPUClockSensorInstance=0x0
CPUClockEntryId=0x6000000

CPUTempSensorId=0xf0000400
CPUTempSensorInstance=0x0
CPUTempEntryId=0x10000fe

CPUPowerSensorId=0xf0002a00
CPUPowerSensorInstance=0x0
CPUPowerEntryId=0x5000000

GPUTempSensorId=0xe0002000
GPUTempSensorInstance=0x14
GPUTempEntryId=0x1000000

GPUUsageSensorId=0xe0002000
GPUUsageSensorInstance=0x14
GPUUsageEntryId=0x7000000

GPUMemSensorId=0xe0002000
GPUMemSensorInstance=0x14
GPUMemEntryId=0x7000008

GPUClockSensorId=0xe0002000
GPUClockSensorInstance=0x14
GPUClockEntryId=0x6000000

GPUPowerSensorId=0xe0002000
GPUPowerSensorInstance=0x14
GPUPowerEntryId=0x5000000

RAMClockSensorId=0xf0000301
RAMClockSensorInstance=0x1
RAMClockEntryId=0x6000000

Drive1TempSensorId=0xf0000100
Drive1TempSensorInstance=0x2
Drive1TempEntryId=0x1000000

Drive2TempSensorId=0xf0000100
Drive2TempSensorInstance=0x0
Drive2TempEntryId=0x1000000

Drive3TempSensorId=0xf0000100
Drive3TempSensorInstance=0x3
Drive3TempEntryId=0x1000000

Drive4TempSensorId=0xf0000100
Drive4TempSensorInstance=0x1
Drive4TempEntryId=0x1000000

Drive5TempSensorId=0xf0000100
Drive5TempSensorInstance=0x4
Drive5TempEntryId=0x1000000

TopIgnored=Idle|%Total|rundll32|wscript|userinit|dwm|Rainmeter|svchost*|System|Memory Compression|WmiPrvSe%|MsMpEng%

; Query for http://openweathermap.org
WeatherQ=Lyon

; Language for http://openweathermap.org
WeatherLang=fr

; API key for http://openweathermap.org
WeatherApiKey=316c550395f164daeb1de82845c3ad98

; Drives letters
Drive1=A:
Drive2=B:
Drive3=C:
Drive4=D:
Drive5=M:
