[Variables]

; Size of the background skin
BgWidth=1024
BgHeight=600

; TDP
CPUTDP=95
GPUTDP=160

; Processes ignored
TopIgnored=rundll32|wscript|userinit|dwm|Rainmeter|svchost*|System|Memory Compression|WmiPrvSe*|MsMpEng*

; Music player
MusicPlayer=Spotify
MusicPlayer2=
PlexToken=
PlexUsername=

; Audio info
RMSGain=10
FFTSensitivity=35

; Query for http://openweathermap.org
WeatherQ=

; API key for http://openweathermap.org
WeatherApiKey=

; Location (https://www.latlong.net)
Latitude=
Longitude=

; API key for https://pro.coinmarketcap.com
CoinMarketCapApiKey=

; Drives letters
Drive1=A:
Drive2=B:
Drive3=C:
Drive4=D:
Drive5=E:
Drive6=F:

; Crypto config
CryptoSparklineWindow=1d
CryptoConvert=USD
CryptoConvertSymbol=$
Coin1=BTC
Coin2=ETH
Coin3=DOGE

; HWiNFO Config (https://www.hwinfo.com/forum/Thread-Rainmeter-plug-in-for-HWiNFO-3-2)
CPUClockSensorId=
CPUClockSensorInstance=
CPUClockEntryId=

CPUTempSensorId=
CPUTempSensorInstance=
CPUTempEntryId=

CPUPowerSensorId=
CPUPowerSensorInstance=
CPUPowerEntryId=

GPUClockSensorId=
GPUClockSensorInstance=
GPUClockEntryId=

GPUTempSensorId=
GPUTempSensorInstance=
GPUTempEntryId=

GPUUsageSensorId=
GPUUsageSensorInstance=
GPUUsageEntryId=

GPUMemSensorId=
GPUMemSensorInstance=
GPUMemEntryId=

GPUMemUsageSensorId=
GPUMemUsageSensorInstance=
GPUMemUsageEntryId=

GPUPowerSensorId=
GPUPowerSensorInstance=
GPUPowerEntryId=

Drive1TempSensorId=
Drive1TempSensorInstance=
Drive1TempEntryId=

Drive2TempSensorId=
Drive2TempSensorInstance=
Drive2TempEntryId=

Drive3TempSensorId=
Drive3TempSensorInstance=
Drive3TempEntryId=

Drive4TempSensorId=
Drive4TempSensorInstance=
Drive4TempEntryId=

Drive5TempSensorId=
Drive5TempSensorInstance=
Drive5TempEntryId=

Drive6TempSensorId=
Drive6TempSensorInstance=
Drive6TempEntryId=

SysFan1SensorId=
SysFan1SensorInstance=
SysFan1EntryId=

SysFan2SensorId=
SysFan2SensorInstance=
SysFan2EntryId=

SysFan3SensorId=
SysFan3SensorInstance=
SysFan3EntryId=

SysFan4SensorId=
SysFan4SensorInstance=
SysFan4EntryId=

MOSTempSensorId=
MOSTempSensorInstance=
MOSTempEntryId=

PCHTempSensorId=
PCHTempSensorInstance=
PCHTempEntryId=

SysTemp1SensorId=
SysTemp1SensorInstance=
SysTemp1EntryId=

SysTemp2SensorId=
SysTemp2SensorInstance=
SysTemp2EntryId=
